app_url: http://localhost:3000
app_name: Crosstower
app_logo: logo.png
app_header_logo: logo.png
base_coin: ETH
app_coin: WETH
auto_approval: true
secret_key_base: b2d96dac611f4a65c84e5c85d16ec9cf90ddd88795d0a57a4fb207745dc9f81a0b4aa336f375dc5bfefb002ca72ba5164b645eb17c566cb5cceb7207d0b1c397
ethereum_provider: https://rinkeby.infura.io/v3/3e19c57faceb42c5a67bd39c08258898
signer_private_key: "6afa484c19a0c13d3d1a7881056fd44231e94224f3c893c619419b9a4016ee20" #Do not keep currencies to this address
coingecko_url: https://api.coingecko.com/api/v3/simple/price
contract_address:
  erc721: '0x428791F08ed8E555192C566b512A73df3b0b06FA'
gasstation_url: https://ethgasstation.info/api/ethgasAPI.json
etherscan:
  api_key: QY75IX1H6YNDAV5P7M9K9VVPNK91UWC5FE
  api_url: https://api-rinkeby.etherscan.io/api
  gas_price: https://api.etherscan.io/api
pinata:
  api_key: 27c0f5fef93ee7a0900e
  api_secret: 91642101ad422ecb1f2596d4f82cb793f09c0d17684549c916c1e73a592b0add
  base_url: https://api.pinata.cloud/pinning/pinFileToIPFS
default_fees:
  service_fee: 2.5
discussion_url: https://govnft.bafdemo.com
support_url: https://faqnft.bafdemo.com
send_email: false # Send email or not
mailer_address: 'smtp.gmail.com' # Enter the server address for your SMTP server
mailer_port: 587 # Enter the port of your SMTP server
mailer_username: smtp_username # Enter your SMTP email username
mailer_password: smtp_password # Enter your SMTP email password
tls_auto: true
exception_sender: inbound.support@yourdomain.com # Enter your exception sender email
exception_recipients: ['support@yourdomain.com'] # Enter your exception recipients email
email_prefix: '[NFT] ' # Enter your exception email prefix
etherscan_url: https://rinkeby.etherscan.io
opensea_url: https://rinkeby-api.opensea.io
chainId: 4
stripe_key: 'sk_test_51L6HiyBmwcLqBgZ0QVhP2fMBlZOXQ5b9c3i8qwiINp7K8189CEUp08mXK0SwB2X63S8HCpNWCDuFRFhaG7wzGF3O00hfRp8iNk'
primary_account: 
  address: '0x13aeb3c8d30fb1a69f32736688af68d49582e3cf'
  private_key: '6afa484c19a0c13d3d1a7881056fd44231e94224f3c893c619419b9a4016ee20'
